server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

# This configuration file, initially contained regular
# expressions to split out labels via the conf. More
# experience has shown that labels can be split out at
# query time. For me, at query time seems to work
# the best. I do perform timestamp extraction, if
# necessary, here.
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: apache
  pipeline_stages:
  static_configs:
  - targets:
     - localhost
    labels:
      job: apache
      __path__: /var/log/apache2/access.log
